---
name: Install MYSQL Package
yum: name=[{ item }] state=installed
with_items: 
  - mysql-server
  - MySQL-python
  - Libselinux-python
  - Libsemanage-python


- name: Configure SE Linux to start mysql on any port.
  seboolean: name=mysql_connect_any state=true persisten=yes
  when:sestaus.rc !=0


- name: Create MYSQL Configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    -restart mysql


- name: Start the MySQL Service
  service: name=mysqld state=started enabled=yes


- name: Insert Iptables Rule
  Lineinfile: dest=/etc/sysconfig/iptables state=present regexp={{ mysql_port }}
      insertafter="^:OUTPUT "  line="-A INPUT -p  tcp --dport {{ mysql_port }} -j ACCEPT"
  notify: restart iptables 
- name: Create Application Database
  mysql_db: name={{ dbname }}  state=present

- name: Create Application DB User
  mysql_user: name{{ dbuser }} passord={{ upassword }} priv=*.*ALL host='%' state=presentt